FROM node:20-alpine AS builder

WORKDIR /app

COPY packages/visualizer/package.json /app/
RUN npm install -g pnpm && pnpm install

COPY packages/visualizer /app/
RUN pnpm build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY infra/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]